<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[onStart]]>
    </line>
    <line>
      <![CDATA[onTestStart for - csk]]>
    </line>
    <line>
      <![CDATA[csk TestCase]]>
    </line>
    <line>
      <![CDATA[onTestFailure for - csk]]>
    </line>
    <line>
      <![CDATA[onTestStart for - dws]]>
    </line>
    <line>
      <![CDATA[dws TestCase]]>
    </line>
    <line>
      <![CDATA[onTestSuccess for - dws]]>
    </line>
    <line>
      <![CDATA[onTestStart for - rcb]]>
    </line>
    <line>
      <![CDATA[onTestSkipped for - rcb]]>
    </line>
    <line>
      <![CDATA[onTestFinished]]>
    </line>
  </reporter-output>
  <suite started-at="2025-02-12T14:24:17 IST" name="Default suite" finished-at="2025-02-12T14:24:31 IST" duration-ms="13741">
    <groups>
    </groups>
    <test started-at="2025-02-12T14:24:17 IST" name="Default test" finished-at="2025-02-12T14:24:31 IST" duration-ms="13741">
      <class name="Listeners.SampleTestCases">
        <test-method signature="csk()[pri:0, instance:Listeners.SampleTestCases@47da3952]" started-at="2025-02-12T14:24:17 IST" name="csk" finished-at="2025-02-12T14:24:27 IST" duration-ms="9773" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [money] but found [mani]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [money] but found [mani]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at Listeners.SampleTestCases.csk(SampleTestCases.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[onTestStart for - csk]]>
            </line>
            <line>
              <![CDATA[csk TestCase]]>
            </line>
            <line>
              <![CDATA[onTestFailure for - csk]]>
            </line>
          </reporter-output>
        </test-method> <!-- csk -->
        <test-method signature="dws()[pri:0, instance:Listeners.SampleTestCases@47da3952]" started-at="2025-02-12T14:24:27 IST" name="dws" finished-at="2025-02-12T14:24:31 IST" duration-ms="3931" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[onTestStart for - dws]]>
            </line>
            <line>
              <![CDATA[dws TestCase]]>
            </line>
            <line>
              <![CDATA[onTestSuccess for - dws]]>
            </line>
          </reporter-output>
        </test-method> <!-- dws -->
        <test-method signature="rcb()[pri:0, instance:Listeners.SampleTestCases@47da3952]" started-at="2025-02-12T14:24:31 IST" name="rcb" finished-at="2025-02-12T14:24:31 IST" depends-on-methods="Listeners.SampleTestCases.csk" duration-ms="1" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Listeners.SampleTestCases.rcb() on instance Listeners.SampleTestCases@47da3952 depends on not successfully finished methods 
[Listeners.SampleTestCases.csk() on instance Listeners.SampleTestCases@47da3952]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Listeners.SampleTestCases.rcb() on instance Listeners.SampleTestCases@47da3952 depends on not successfully finished methods 
[Listeners.SampleTestCases.csk() on instance Listeners.SampleTestCases@47da3952]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[onTestSkipped for - rcb]]>
            </line>
            <line>
              <![CDATA[onTestFinished]]>
            </line>
          </reporter-output>
        </test-method> <!-- rcb -->
      </class> <!-- Listeners.SampleTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
